SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_SPEED = 300
PLAYER_TURN_SPEED = 300
PLAYER_SHOT_SPEED = 1000
PLAYER_SHOOT_COOLDOWN = 0.2

SHOT_RADIUS = 5

# Reward system
SURVIVAL_REWARD_PER_SECOND = 0  # Additional reward for surviving longer

# Difficulty scaling
LEVEL_DURATION = 30.0  # 30 seconds per level
ASTEROID_SPEED_INCREASE_PER_LEVEL = 0.15  # 15% speed increase per level
